name: base_flutter_mvvm_getx_app
description: "Base Flutter App Based on MVVM Architecture and GetX State Manager"
homepage: https://resam.site
repository: https://github.com/reesaam/base_flutter_mvvm_getx_app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0

environment:
  sdk: ">=3.11.0 <4.0.0"

features:
  dot-shorthands: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Main
  get: ^4.7.3
  freezed: ^3.2.0
  json_annotation: ^4.12.0
  getx_binding_annotation: ^0.4.1

  # Storage
  shared_preferences: ^2.5.5
  get_storage: ^2.1.1
  get_secure_storage: ^1.0.5

  # Device Related
  permission_handler: ^12.0.3
  path_provider: ^2.1.6
  url_launcher: ^6.3.2
  app_links: ^7.0.0

  # Tools
  dartz: ^0.10.1

  # Connection
  dio: ^5.10.0
  #http: ^1.6.0
  html: ^0.15.6
  connectivity_plus: ^7.2.0
  internet_connection_checker_plus: ^3.1.1

  # Notification
  awesome_notifications: ^0.12.1

  # UI
  flutter_animate: ^4.5.2
  auto_size_text: ^3.0.0
  mask_text_input_formatter: ^2.9.0
  flutter_regex: ^0.0.3

  # File
#  open_file_plus: ^3.4.1+1
  flutter_file_dialog: ^3.0.3

  # Localization
  i69n: ^3.6.0
  timezone: ^0.11.1
  country_flags: ^4.1.2

  # Share
  share_plus: ^13.2.0

  # Package
  rename: ^3.1.0
  rename_app: ^1.6.6
  change_app_package_name: ^1.5.0

  # Other
  #flutter_native_splash: ^2.4.8

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.15.1
  getx_binding_annotation_generator: ^0.4.1
  json_serializable: ^6.14.0
  freezed_annotation: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

#dependency_overrides:
#    analyzer: 8.1.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
