enum APIResponseStatus {
  success(statusCode: 200, isSuccess: true),
  created(statusCode: 201, isSuccess: true),
  nonAuthoritativeInformationException(statusCode: 203),
  noContentException(statusCode: 204),
  notModifiedException(statusCode: 304),
  unauthorizedException(statusCode: 401),
  paymentRequiredException(statusCode: 402),
  forbiddenException(statusCode: 403),
  notFoundException(statusCode: 404),
  methodNotAllowedException(statusCode: 405),
  notAcceptableException(statusCode: 406),
  proxyAuthRequiredException(statusCode: 407),
  requestTimeoutException(statusCode: 408),
  conflictException(statusCode: 409),
  lengthRequiredException(statusCode: 411),
  preConditionFailedException(statusCode: 412),
  requestEntityTooLargeException(statusCode: 413),
  requestUriTooLongException(statusCode: 414),
  unsupportedMediaTypeException(statusCode: 415),
  requestedRangeNotSatisfiableException(statusCode: 416),
  expectationFailedException(statusCode: 417),
  unProcessableEntityException(statusCode: 422),
  failedDependencyException(statusCode: 424),
  unorderedCollectionException(statusCode: 425),
  upgradeRequiredException(statusCode: 426),
  tooManyRequestException(statusCode: 429),
  requestHeaderFieldsTooLargeException(statusCode: 431),
  noResponseException(statusCode: 444),
  unavailableForLegalReasonsException(statusCode: 451),
  requestHeaderTooLargeException(statusCode: 494),
  internalServerErrorException(statusCode: 500),
  notImplementedException(statusCode: 501),
  badGatewayException(statusCode: 502),
  serviceUnavailableException(statusCode: 503),
  gatewayTimeoutException(statusCode: 504),
  insufficientStorageException(statusCode: 507),
  loopDetectedException(statusCode: 508),
  bandwidthLimitException(statusCode: 509),
  notExtendedException(statusCode: 510),
  networkAuthRequiredException(statusCode: 511),
  unknownException(statusCode: 0);

  final int statusCode;
  final bool? isSuccess;
  const APIResponseStatus({required this.statusCode, this.isSuccess});
}
