import 'dart:io';

import 'package:yaml/yaml.dart';

class BarrelsGenerator {
  BarrelsGenerator({Directory? projectRoot}) : root = projectRoot ?? _findProjectRoot();

  final Directory root;

  File get configFile => File('${root.path}${Platform.pathSeparator}config${Platform.pathSeparator}barrels.yaml');

  int generate({bool checkOnly = false}) {
    if (!configFile.existsSync()) {
      throw StateError('Missing config: ${configFile.path}');
    }

    final yaml = loadYaml(configFile.readAsStringSync()) as YamlMap;
    final excludeSuffixes = _stringList(yaml['exclude_suffixes']);
    final excludeNames = _stringList(yaml['exclude_names']).toSet();
    final excludePrivate = yaml['exclude_private'] != false;
    final excludePartFiles = yaml['exclude_part_files'] != false;
    final barrels = yaml['barrels'] as YamlList? ?? YamlList();

    var changed = 0;
    var stale = 0;

    for (final raw in barrels) {
      final barrel = raw as YamlMap;
      final outputRel = barrel['output'] as String;
      final outputFile = File('${root.path}${Platform.pathSeparator}${outputRel.replaceAll('/', Platform.pathSeparator)}');
      final content = _generateBarrel(
        barrel: barrel,
        excludeSuffixes: excludeSuffixes,
        excludeNames: excludeNames,
        excludePrivate: excludePrivate,
        excludePartFiles: excludePartFiles,
      );

      if (checkOnly) {
        if (!outputFile.existsSync() || outputFile.readAsStringSync() != content) {
          stale++;
        }
        continue;
      }

      outputFile.parent.createSync(recursive: true);
      final previous = outputFile.existsSync() ? outputFile.readAsStringSync() : null;
      if (previous != content) {
        outputFile.writeAsStringSync(content);
        changed++;
      }
    }

    if (checkOnly && stale > 0) {
      throw StateError('$stale barrel(s) out of date. Run: dart run tool/generate_barrels.dart');
    }
    return changed;
  }

  String _generateBarrel({
    required YamlMap barrel,
    required List<String> excludeSuffixes,
    required Set<String> excludeNames,
    required bool excludePrivate,
    required bool excludePartFiles,
  }) {
    final library = barrel['library'] == true;
    final packageExports = _stringList(barrel['package_exports']);
    final roots = _stringList(barrel['roots']);
    final files = _stringList(barrel['files']);
    final extraExports = _stringList(barrel['extra_exports']);
    final includeSuffixes = _stringList(barrel['include_suffixes']);
    final localExclude = _stringList(barrel['exclude']).toSet();

    final exports = <String>{};

    for (final pkg in packageExports) {
      exports.add("export '$pkg';");
    }

    final rootPosix = root.path.replaceAll('\\', '/');

    for (final rootRel in roots) {
      final dir = Directory('$rootPosix/$rootRel');
      if (!dir.existsSync()) continue;
      for (final entity in dir.listSync(recursive: true)) {
        if (entity is! File) continue;
        final path = entity.path.replaceAll('\\', '/');
        if (!path.endsWith('.dart')) continue;
        final rel = path.substring(rootPosix.length + 1);
        if (!_shouldExport(
          file: entity,
          relPath: rel,
          excludeSuffixes: excludeSuffixes,
          excludeNames: excludeNames,
          excludePrivate: excludePrivate,
          excludePartFiles: excludePartFiles,
          includeSuffixes: includeSuffixes,
          localExclude: localExclude,
        )) {
          continue;
        }
        exports.add(_toExport(rel));
      }
    }

    for (final fileRel in [...files, ...extraExports]) {
      final normalized = fileRel.replaceAll('\\', '/');
      final file = File('$rootPosix/$normalized');
      if (!file.existsSync()) continue;
      if (!_shouldExport(
        file: file,
        relPath: normalized,
        excludeSuffixes: excludeSuffixes,
        excludeNames: excludeNames,
        excludePrivate: excludePrivate,
        excludePartFiles: excludePartFiles,
        includeSuffixes: includeSuffixes,
        localExclude: localExclude,
      )) {
        continue;
      }
      exports.add(_toExport(normalized));
    }

    final sorted = exports.toList()..sort();
    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..writeln('// Generated by: dart run tool/generate_barrels.dart')
      ..writeln('// Config: config/barrels.yaml')
      ..writeln();
    if (library) {
      buffer
        ..writeln('library;')
        ..writeln();
    }
    for (final line in sorted) {
      buffer.writeln(line);
    }
    return buffer.toString();
  }

  static bool _shouldExport({
    required File file,
    required String relPath,
    required List<String> excludeSuffixes,
    required Set<String> excludeNames,
    required bool excludePrivate,
    required bool excludePartFiles,
    required List<String> includeSuffixes,
    required Set<String> localExclude,
  }) {
    final name = relPath.split('/').last;
    if (excludeNames.contains(name)) return false;
    if (localExclude.contains(relPath) || localExclude.contains(name)) return false;
    if (excludePrivate && name.startsWith('_')) return false;

    final allowedByInclude = includeSuffixes.isEmpty ? relPath.endsWith('.dart') : includeSuffixes.any(relPath.endsWith);
    if (!allowedByInclude) return false;

    for (final suffix in excludeSuffixes) {
      if (relPath.endsWith(suffix)) return false;
    }

    if (excludePartFiles) {
      try {
        final content = file.readAsStringSync();
        final lines = content.split('\n');
        for (final line in lines) {
          final t = line.trimLeft();
          if (t.isEmpty || t.startsWith('//') || t.startsWith('/*') || t.startsWith('*')) {
            continue;
          }
          if (t.startsWith('part of ')) return false;
          break;
        }
      } catch (_) {
        return false;
      }
    }

    return true;
  }

  static String _toExport(String libRelativePath) {
    final withoutLib = libRelativePath.startsWith('lib/') ? libRelativePath.substring('lib/'.length) : libRelativePath;
    return "export '../$withoutLib';";
  }

  static List<String> _stringList(dynamic value) {
    if (value == null) return const [];
    if (value is YamlList) return value.map((e) => e.toString()).toList();
    if (value is List) return value.map((e) => e.toString()).toList();
    return const [];
  }

  static Directory _findProjectRoot() {
    var dir = Directory.current;
    while (true) {
      if (File('${dir.path}${Platform.pathSeparator}pubspec.yaml').existsSync()) return dir;
      final parent = dir.parent;
      if (parent.path == dir.path) {
        throw StateError('Could not find pubspec.yaml from ${Directory.current.path}');
      }
      dir = parent;
    }
  }
}
