import '../../barrels/ui_kit_barrel.dart';
import 'snackbar_widget.dart';

/// [Input] word at the of the variables
/// is because most of the variables with their names will shadow the Original variables
/// of the [GetSnackBar] Component

class AppSnackBar<T> extends AppSnackBarWidget<T> {
  const AppSnackBar.general({
    super.key,
    super.titleInput,
    super.borderColorInput,
    super.borderRadiusInput,
    super.onTapInput,
    super.widgetInput,
    super.titleColorInput,
    super.messageInput,
    super.messageColorInput,
    super.iconInput,
    super.iconColorInput,
    super.leadingIconInput,
    super.leadingIconColorInput,
    super.leadingTextInput,
    super.leadingActionInput,
    super.leadingTextColorInput,
    super.buttonActionInput,
    super.buttonTextInput,
    super.buttonColorInput,
    super.buttonTextColorInput,
    super.crossAxisAlignment,
    super.isDismissibleInput,
    super.iconPulseInput,
    super.paddingInput,
    super.marginInput,
    super.durationInput,
    super.showProgressIndicatorInput,
    super.progressIndicatorBackgroundColorInput,
    super.progressIndicatorControllerInput,
  }) : super();

  const AppSnackBar.info({
    super.key,
    super.titleInput,
    super.borderColorInput,
    super.borderRadiusInput,
    super.onTapInput,
    super.widgetInput,
    super.titleColorInput,
    super.messageInput,
    super.messageColorInput,
    super.iconInput,
    super.iconColorInput,
    super.leadingIconInput,
    super.leadingIconColorInput,
    super.leadingTextInput,
    super.leadingActionInput,
    super.leadingTextColorInput,
    super.buttonActionInput,
    super.buttonTextInput,
    super.buttonColorInput,
    super.buttonTextColorInput,
    super.crossAxisAlignment,
    super.isDismissibleInput,
    super.iconPulseInput,
    super.paddingInput,
    super.marginInput,
    super.durationInput,
    super.showProgressIndicatorInput,
    super.progressIndicatorBackgroundColorInput,
    super.progressIndicatorControllerInput,
  }) : super();

  const AppSnackBar.warning({
    super.key,
    super.titleInput,
    super.borderColorInput = AppColors.transparent,
    super.borderRadiusInput,
    super.onTapInput,
    super.widgetInput,
    super.titleColorInput,
    super.messageInput,
    super.messageColorInput,
    super.iconInput,
    super.iconColorInput,
    super.leadingIconInput,
    super.leadingIconColorInput,
    super.leadingTextInput,
    super.leadingActionInput,
    super.leadingTextColorInput,
    super.buttonActionInput,
    super.buttonTextInput,
    super.buttonColorInput,
    super.buttonTextColorInput,
    super.crossAxisAlignment,
    super.isDismissibleInput,
    super.iconPulseInput,
    super.paddingInput,
    super.marginInput,
    super.durationInput,
    super.showProgressIndicatorInput,
    super.progressIndicatorBackgroundColorInput,
    super.progressIndicatorControllerInput,
  }) : super(backgroundColorInput: AppColors.warning);

  const AppSnackBar.error({
    super.key,
    super.titleInput,
    super.borderColorInput = AppColors.transparent,
    super.borderRadiusInput,
    super.onTapInput,
    super.widgetInput,
    super.titleColorInput,
    super.messageInput,
    super.messageColorInput,
    super.iconInput,
    super.iconColorInput,
    super.leadingIconInput,
    super.leadingIconColorInput,
    super.leadingTextInput,
    super.leadingActionInput,
    super.leadingTextColorInput,
    super.buttonActionInput,
    super.buttonTextInput,
    super.buttonColorInput,
    super.buttonTextColorInput,
    super.crossAxisAlignment,
    super.isDismissibleInput,
    super.iconPulseInput,
    super.paddingInput,
    super.marginInput,
    super.durationInput,
    super.showProgressIndicatorInput,
    super.progressIndicatorBackgroundColorInput,
    super.progressIndicatorControllerInput,
  }) : super(backgroundColorInput: AppColors.error);
}
