// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: dart run tool/generate_barrels.dart
// Config: config/barrels.yaml
// Exports: 3

library;

export '../core/annotations/freezed_custom_annotation.dart';
export '../core/annotations/notifications_annotations.dart';
export 'package:getx_binding_annotation/getx_binding_annotation.dart';
