// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: dart run tool/generate_barrels.dart
// Config: config/barrels.yaml

library;

export '../core/core_resources/apis.dart';
export '../core/core_resources/assert_texts.dart';
export '../core/core_resources/core_enums.dart';
export '../core/core_resources/core_flags.dart';
export '../core/core_resources/countries.dart';
export '../core/core_resources/defaults.dart';
export '../core/core_resources/defined_types.dart';
export '../core/core_resources/fonts.dart';
export '../core/core_resources/icons.dart';
export '../core/core_resources/images.dart';
export '../core/core_resources/logos.dart';
export '../core/core_resources/page_details.dart';
export '../core/core_resources/system_channel_methods.dart';
export '../core/core_resources/texts.dart';
