// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: dart run tool/generate_barrels.dart
// Config: config/barrels.yaml
// Exports: 10

library;

export '../core/app_routing/app_routing.dart';
export '../core/core_functions.dart';
export '../core/core_info/app_info.dart';
export '../core/core_info/core_defaults.dart';
export '../core/core_info/developer_info.dart';
export '../core/flavors/env_config.dart';
export '../core/core_layout/adaptive_builder.dart';
export 'package:flutter/material.dart';
export 'package:flutter/widgets.dart';
export 'package:get/get.dart';
