// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: dart run tool/generate_barrels.dart
// Config: config/barrels.yaml
// Exports: 5

library;

export '../localization/localizations.dart';
export '../localization/translation.i69n.dart';
export '../localization/translation_fa.i69n.dart';
export 'package:flutter_localizations/flutter_localizations.dart';
export 'package:timezone/timezone.dart';
