// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: dart run tool/generate_barrels.dart
// Config: config/barrels.yaml
// Exports: 1

library;

export '../shared/shared_widgets/empty_page_widget.dart';
